### ISSUE TITLE
「【依頼】ChatSpace挙動確認」

### ISSUE THREAD

**Issue by HosoRo** [HosoRo/chat-space#9]
# IPアドレス
54.248.30.202

**Comment by mutorisa** [comment]
ご提出ありがとうございます！！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**①グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう**

[参考]
https://master.tech-camp.in/curriculums/4278

<img width="1374" alt="修正" src="https://user-images.githubusercontent.com/65144927/86865299-b85a1800-c109-11ea-9020-71fcc2044718.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by HosoRo** [comment]
修正しました！

![output](https://user-images.githubusercontent.com/64320928/86891167-5b765600-c139-11ea-8f83-77e65d9fb017.gif)

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！
